# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  combined-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Call Reusable Workflow 1
        uses: ./.github/workflows/reusable-workflow-1.yml
        with:
          example-input-1: "Hello from main workflow to workflow 1"

      - name: Call Reusable Workflow 2
        uses: ./.github/workflows/reusable-workflow-2.yml
        with:
          example-input-2: "Hello from main workflow to workflow 2"


# name: CD

# on:
#   workflow_dispatch: 
#     inputs:
#       major:
#         description: Year
#         type: number 
#         required: true
#         default: '24'
#       minor:
#         description: Release
#         type: number 
#         required: true
#         default: '4'
#       build:
#         description: Beta
#         type: number 
#         required: true
#         default: '0'
#       revision:
#         description: Alpha
#         type: number 
#         required: true
#         default: '0'
#       SSLCert:
#         description: "Add Certificate"
#         type: choice
#         required: true
#         default: 'No'
#         options:
#           - 'Yes'
#           - 'No'
          
# jobs:
#   Create-version-Number:
#     runs-on: ubuntu-latest
#     steps:
#       - name : Create-version-Number1 
#         uses: ./.github/workflows/Create-version-Number.yml
#         with:
#           inherit-secrets: true

#       - name : Create-version-Number2 
#         uses: ./.github/workflows/Create-version-Number2.yml
#         with:
#           inherit-secrets: true


               
#   # CI:
#   #   name: CI
#   #   needs: Create-version-Number
#   #   uses: ./.github/workflows/CI-2.yml
#   #   secrets: inherit
    
#   # Release:
#   #   name: Release
#   #   needs: CI
#   #   uses: ./.github/workflows/Release-2.yml
#   #   secrets: inherit
    
#   # Deploy:
#   #   name: Deploy
#   #   needs: Release
#   #   uses: ./.github/workflows/Deploy-2.yml

#   # Docker:
#   #   name: Docker
#   #   needs: CI
#   #   uses: ./.github/workflows/Docker.yml
#   #   secrets: inherit

